export const COUNT_TOTAL_PRICE = 'COUNT_TOTAL_PRICE',
	GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST',
	GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS',
	GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';
