export const COUNT_TOTAL_PRICE = 'COUNT_TOTAL_PRICE',
	OPEN_INGREDIENT_MODAL = 'OPEN_INGREDIENT_MODAL',
	CLOSE_INGREDIENT_MODAL = 'CLOSE_INGREDIENT_MODAL',
	GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST',
	GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS',
	GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';
